### ISSUE TITLE
Have a Question

### ISSUE THREAD

**Issue by TheGridRepo** [henryjfry/fryhenryj#5]
Hi Mate wasn't sure how to contact you on social media... not sure if your the original creator of  A Pirates Life for Me kodi addon from back in the day...well i still have the old zip file for which i'm looking to bring back to life...with your permission. have it installed and running on kodi 20.5 but with some minor glitches not a pro at python was hoping you can give me some insite to the error im receving. if you like can send you the zip file somehow to see me edites

**Comment by henryjfry** [comment]
What addon?
I have some responsibility for a couple of addons but that one isn't one that rings any bells
However if someone copied something I did post and you are having issues I am willing to help in a very limited capacity

So if you want to post some logs and maybe the zip of the addon I'll be able to figure out who broke what in whatever code they stole.

**Comment by TheGridRepo** [comment]
[kodi.log](https://github.com/henryjfry/fryhenryj/files/14825716/kodi.log)
[plugin.video.pirateslife4me-12.0.zip](https://github.com/henryjfry/fryhenryj/files/14825717/plugin.video.pirateslife4me-12.0.zip)
i have attacted the original default.py as original

**Comment by henryjfry** [comment]
Yeah wherever that addon came from it wasn't me.
I'm going to look at it but I'm half cut right now so it'll be tomorrow at the earliest

**Comment by TheGridRepo** [comment]
https://bestforkodi.com/guide-install-a-pirates-life-for-me-kodi-addon-repo/    this was the original auther of the addon.

**Comment by TheGridRepo** [comment]
thanks well appriciated...

**Comment by TheGridRepo** [comment]
Hi mate i think the code has to do with resolverurl import kodi.py 

def create_item(queries, label, thumb='', fanart='', is_folder=None, is_playable=None, total_items=0, menu_items=None, replace_menu=False):
    list_item = xbmcgui.ListItem(label, iconImage=thumb, thumbnailImage=thumb)
    add_item(queries, list_item, fanart, is_folder, is_playable, total_items, menu_items, replace_menu)

the way its reading the deafault.py in the code for.
def main_menu3():

    kodi.create_item({'mode': ""}, '[COLOR gold]Pirate Bay Top Trending Movies for last 48 hours[/COLOR]', is_folder=False, is_playable=False)

    GetTorLinks('https://pirateproxylive.org/top/201')

**Comment by henryjfry** [comment]
Right well i had absolutely nothing to do with this addon but from "default ----original.py" to "default.py" you have removed a line:

"import kodi"

And the error:

"kodi.create_item({'mode': ""}, '[COLOR gold]Pirate Bay Top HD TV Shows for last 48 hours[/COLOR]', is_folder=False, is_playable=False)"
"NameError: name 'kodi' is not defined"


Is because there is no "kodi" module.


However there are actual XBMC modules:

import xbmcaddon
import xbmcvfs
import os,xbmc
import xbmcplugin

Which can be imported in python.  But the kodi module doesnt exist and original must have been a wrapper someone wrote to abstract a bunch of internal kodi functions.

Id suggest find a version of the addon which contained that "kodi.py" file and figure out from there what you need to fix.

However I dont envy you the challenge as that addon looks like a total mess.

**Comment by henryjfry** [comment]
So yes you have effectively identified the issue, there is no "create_item" function because there is no "kodi.py" module.

But if this addon was built around that "kodi.py" file to act as a wrapper for something like:

````
list_item = xbmcgui.ListItem(label, iconImage=thumb, thumbnailImage=thumb)
add_item(queries, list_item, fanart, is_folder, is_playable, total_items, menu_items, replace_menu)
````

You would need to ensure to replicate every function the original "kodi.py" was providing.

**Comment by henryjfry** [comment]
How exactly have you identified me as being connected with this addon?  I have never even heard of it, let alone used it, let alone coded a single line.

So all I can provide is very general guidance as I have absolutely no appetite to figure out how that random addon might possibly work, if all the hard coded links aren't already hopelessly out of date.

**Comment by TheGridRepo** [comment]
With the extended info mod...diamond name...thought you the one since the repo the author used to be called the same name. 

Sent from AOL on Android 
 
  On Wed, Apr 3, 2024 at 6:58 a.m., ***@***.***> wrote:   


How exactly have you identified me as being connected with this addon? I have never even heard of it, let alone used it, let alone coded a single line.

So all I can provide is very general guidance as I have absolutely no appetite to figure out how that random addon might possibly work, if all the hard coded links are hopelessly out of date.

**Comment by TheGridRepo** [comment]
It's just the kodicreate_item that I'm trying to figure out.

Sent from AOL on Android 
 
  On Wed, Apr 3, 2024 at 6:51 a.m., ***@***.***> wrote:   


Right well i had absolutely nothing to do with this addon but from "default ----original.py" to "default.py" you have removed a line:

"import kodi"

And the error:

"kodi.create_item({'mode': ""}, '[COLOR gold]Pirate Bay Top HD TV Shows for last 48 hours[/COLOR]', is_folder=False, is_playable=False)"
"NameError: name 'kodi' is not defined"

Is because there is no "kodi" module.

However there are actual XBMC modules:

import xbmcaddon
import xbmcvfs
import os,xbmc
import xbmcplugin

Which can be imported in python. But the kodi module doesnt exist and original must have been a wrapper someone wrote to abstract a bunch of internal kodi functions.

Id suggest find a version of the addon which contained that "kodi.py" file and figure out from there what you need to fix.

However I dont envy you the challenge as that addon looks like a total mess.

**Comment by henryjfry** [comment]
I suggest you find an original versoin of the addon which contains this function and recreate it.

I could hazard a guess how you would need to do that but without testing anything, which i dont want to do and would likely take some work on my part, I cant just spit out code for you.

If you want someone to solve your problem for you i suggest you find a more tolerant person.
Or start talking to chatgpt.

**Comment by henryjfry** [comment]
Some random guy who "wanted help" updating diamond info mod for Python3 roped me into talking ownership of this repo.
He asked me to do all sorts of stuff, provided next to no help, was demanding and didnt have any idea what he was doing.
He said he could code in python and VBA but that was clearly lies as he knew nothing.

So he probably stole that addon and did a terrible job of maintaining it. He is part of the reason why my addon has a tonne of undocumented features that I dont care to advertise, because as soon as his immediate problems were resolved he disappeared and wouldnt even help me test anything.

So that may explain why i'm unwilling to help someone fix a random addon who clearly doesnt know what they are doing, would leave me doing the lions share of the work, and may then turn around and profit off my efforts.
No thank you, not again.


> With the extended info mod...diamond name...thought you the one since the repo the author used to be called the same name.  Sent from AOL on Android On Wed, Apr 3, 2024 at 6:58 a.m., ***@***.***> wrote: How exactly have you identified me as being connected with this addon? I have never even heard of it, let alone used it, let alone coded a single line. So all I can provide is very general guidance as I have absolutely no appetite to figure out how that random addon might possibly work, if all the hard coded links are hopelessly out of date. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
